target: sin_1000x

# 模型参数
in_features: 1
hidden_features: 256
hidden_layers: 4
out_features: 1

#s_min: [1, 1, 1, 0]
#s_max: [5.5, 5.5, 5.5, 0.8]


# 训练参数
epochs: 10000
lr: 0.0001
lr_min: 1e-7
n_train: 8000
batch_size: 8000
seed: 42
