model: msa
images: [astronaut]

hidden_features: 256
hidden_layers: 4
out_features: 3
#s_min: [1.2, 1.2, 1.2, 0]
#s_max: [3.6, 3.6, 3.6, 1.0]
#mode: 'sin+fr'
#mapping_size: 512
#scale: 10

seed: 42
in_features: 2
epochs: 5000
lr: 0.001
lr_min: 1e-4

