model: msa
data_path: data/dragon.mat

epochs: 200
lr: 0.005

batch_size: 500000
hidden_features: 256
hidden_layers: 3
out_features: 1

seed: 42
#s_min: [1, 1, 1]
#s_max: [1.8, 1.8, 1.8]
